# -*- coding: utf-8 -*-
"""Lista de atividades | Python 01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zNI9SyRPmJ4oOgnxiBVSdMlxcWGFnPK9

Lista de atividades | Python 01

1 - Faça um algoritmo que leia os valores A, B, C e imprima na tela se a soma de A + B é menor que C.
"""

A = input("Digite o valor de A: ")
B = input("Digite o valor de B: ")
C = input("Digite o valor de C: ")

if A + B < C:
    print("A soma de A + B é menor que C.")
else:
    print("A soma de A + B não é menor que C.")

#Neste caso eu tenho que especificar "float()" antes do input, para representar um número inteiro?

"""2) Faça um algoritmo que leia o nome, o sexo e o estado civil de uma pessoa. Caso sexo seja “F” e
estado civil seja “CASADA”, solicitar o tempo de casada (anos).
"""

nome = input("Digite seu nome: ")
sexo = input("Digite seu sexo (F/M): ")
estado_civil = input("Qual seu estado civil (em maiusculo): ")

if sexo =="F" and estado_civil == "CASADA":
 tempo_casado = input("Quanto tempo de casado você tem? (Em anos, por favor)")

 #Tranquilo

"""3) Faça um algoritmo para receber um número qualquer e informar na tela se é par ou ímpar.

> Adicionar aspas



"""

X = int(input("Digite um número: "))

if X % 2 == 0:
    print("O número é par.")
else:
    print("O número é ímpar.")

#Tranquilo

"""4) Faça um algoritmo que leia dois valores inteiros A e B se os valores forem iguais deverá se
somar os dois, caso contrário multiplique A por B. Ao final de qualquer um dos cálculos deve-se
atribuir o resultado para uma variável C e mostrar seu conteúdo na tela.
"""

A = int(input("Digite o valor de A: "))
B = int(input("Digite o valor de B: "))

if A == B:
    C = A + B
else:
    C = A * B

print("O valor de C é: ", C)

"""5) Encontrar o dobro de um número caso ele seja positivo e o seu triplo caso seja negativo,
imprimindo o resultado.
"""

A = int(input("Digite o valor de A: "))

if A > 0:
    B = A * 2
else:
    B = A * 3

print("O valor de B é: ", B)

"""6) Escreva um algoritmo que lê dois valores booleanos (lógicos) e então determina se ambos são
VERDADEIROS ou FALSOS.
"""

A = input("Digite o valor de A (True/False): ").capitalize() == "True"
B = input("Digite o valor de B (True/False): ").capitalize() == "True"


if A and B:
    print("Ambos são verdadeiros.")
elif not A and not B:
    print("Ambos são falsos.")
else:
    print("A e B têm valores diferentes.")


#Vi que ".capitalize()" para garantir que a string digitada (True ou False) seja tratada corretamente independentemente de como o usuário insere o valor (minúsculas ou maiúsculas).

"""

```
# Isto está formatado como código
```

7) Faça um algoritmo que leia uma variável e some 5 caso seja par ou some 8 caso seja ímpar,
imprimir o resultado desta operação."""

A = int(input("Digite o valor de A: "))

if A % 2 == 0:
    B = A + 5
else:
    B = A + 8

print("O valor de B é: ", B)

"""*8*) Escreva um algoritmo que leia três valores inteiros e diferentes e

---

mostre-os em ordem
decrescente.
"""

A = int(input("Digite o valor de A: "))
B = int(input("Digite o valor de B: "))
C = int(input("Digite o valor de C: "))

valores = [A, B, C]

valores_ordenados = sorted(valores, reverse=True)

print("Valores em ordem decrescente:", valores_ordenados)

"""9) Tendo como dados de entrada a altura e o sexo de uma pessoa, construa um algoritmo que
calcule seu peso ideal, utilizando as seguintes fórmulas:
● para homens: (72.7 * h) – 58;
● para mulheres: (62.1 * h) – 44.7.
"""

altura = float(input("Digite a altura em metros (por ex, 1.75): "))
sexo = input("Digite o sexo (M/F): ").upper()

if sexo == "M":
    peso_ideal = (72.7 * altura) - 58
    print(f"O peso ideal para um homem de {altura} metros é: {peso_ideal:.2f} kg")

elif sexo == "F":
    peso_ideal = (62.1 * altura) - 44.7
    print(f"O peso ideal para uma mulher de {altura} metros é: {peso_ideal:.2f} kg")
#O elif é uma abreviação de "else if" em Python. "elif" permite que você adicione mais condições a um bloco if.


else:
    print("Sexo inválido! Digite M para masculino ou F para feminino.")

"""10) O IMC – Indice de Massa Corporal é um critério da Organização Mundial de Saúde para dar
umaindicação sobre a condição de peso de uma pessoa adulta. A fórmula é IMC = peso / ( altura )2

Elabore um algoritmo que leia o peso e a altura de um adulto e mostre sua condição de acordo
com a tabela abaixo.
IMC em adultos Condição
Abaixo de 18,5 Abaixo do peso
Entre 18,5 e 25 Peso normal
Entre 25 e 30 Acima do peso
Acima de 30 obeso
"""

peso = float(input("Digite o peso em kg: "))
altura = float(input("Digite a altura em metros (por exemplo, 1.75): "))

imc = peso / (altura ** 2)

if imc < 18.5:
    condicao = "Abaixo do peso"
elif 18.5 <= imc < 25:
    condicao = "Peso normal"
elif 25 <= imc < 30:
    condicao = "Acima do peso"
else:
    condicao = "Obeso"

print(f"Seu IMC é {imc:.2f}. Condição: {condicao}.")

#Achei que tava errado, foi até bom saber

"""11) Elabore um algoritmo que calcule o que deve ser pago por um produto, considerando o preço
normal deetiqueta e a escolha da condição de pagamento. Utilize os códigos da tabela a seguir
para ler qual acondição de pagamento escolhida e efetuar o cálculo adequado.
Código Condição de pagamento
1 À vista em dinheiro ou cheque, recebe 10% de desconto
2 À vista no cartão de crédito, recebe 15% de desconto
3 Em duas vezes, preço normal de etiqueta sem juros
4 Em duas vezes, preço normal de etiqueta mais juros de 10%
"""

preco_normal = float(input("Digite o preço normal do produto em reais: "))

print("Escolha a condição de pagamento:")
print("1 - À vista em dinheiro ou cheque (10% de desconto)")
print("2 - À vista no cartão de crédito (15% de desconto)")
print("3 - Em duas vezes (sem juros)")
print("4 - Em duas vezes (com juros de 10%)")
codigo_pagamento = int(input("Digite o código da condição de pagamento: "))

if codigo_pagamento == 1:
    valor_a_pagar = preco_normal * 0.90
    print(f"Valor a ser pago à vista em dinheiro ou cheque: R${valor_a_pagar:.2f}")
elif codigo_pagamento == 2:
    valor_a_pagar = preco_normal * 0.85
    print(f"Valor a ser pago à vista no cartão de crédito: R${valor_a_pagar:.2f}")
elif codigo_pagamento == 3:
    valor_a_pagar = preco_normal
    print(f"Valor a ser pago em duas vezes: R${valor_a_pagar:.2f}")
elif codigo_pagamento == 4:
    valor_a_pagar = preco_normal * 1.10
    print(f"Valor a ser pago em duas vezes com juros: R${valor_a_pagar:.2f}")
else:
    print("Código de pagamento inválido. Escolha um código entre 1 e 4.")

#bem complexo

"""12) Escreva um algoritmo que leia o número de identificação, as 3 notas obtidas por um aluno nas
3 verificações e a média dos exercícios que fazem parte da avaliação, e calcule a média de
aproveitamento, usando a fórmula:
MA := (nota1 + nota 2 * 2 + nota 3 * 3 + ME)/7
A atribuição dos conceitos obedece a tabela abaixo. O algoritmo deve escrever o número do aluno,
suas notas, a média dos exercícios, a média de aproveitamento, o conceito correspondente e a
mensagem 'Aprovado' se o conceito for A, B ou C, e 'Reprovado' se o conceito for D ou E.
Média de aproveitamento Conceito
>= 90 A
>= 75 e < 90 B
>= 60 e < 75 C
>= 40 e < 60 D
< 40 E
"""

numero_id = input("Digite o número de identificação do aluno: ")

nota1 = float(input("Digite a nota 1: "))
nota2 = float(input("Digite a nota 2: "))
nota3 = float(input("Digite a nota 3: "))

media_exercicios = float(input("Digite a média dos exercícios: "))

ma = (nota1 + nota2 * 2 + nota3 * 3 + media_exercicios) / 7

if ma >= 90:
    conceito = 'A'
    situacao = 'Aprovado'
elif 75 <= ma < 90:
    conceito = 'B'
    situacao = 'Aprovado'
elif 60 <= ma < 75:
    conceito = 'C'
    situacao = 'Aprovado'
elif 40 <= ma < 60:
    conceito = 'D'
    situacao = 'Reprovado'
else:
    conceito = 'E'
    situacao = 'Reprovado'

print(f"Número do aluno: {numero_id}")
print(f"Notas: {nota1}, {nota2}, {nota3}")
print(f"Média dos exercícios: {media_exercicios:.2f}")
print(f"Média de aproveitamento: {ma:.2f}")
print(f"Conceito: {conceito}")
print(f"Situação: {situacao}")