# -*- coding: utf-8 -*-
"""Lista de atividades | Python 02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KCykfz3flnCSGjUcCYM3OJjvfHPGlvgd

Lista de atividades | Python 02

1) Desenvolver um algoritmo que efetue a soma de todos os números ímpares que são múltiplos de
três e que se encontram no conjunto dos números de 1 até 500.
"""

soma = 0
for i in range(1, 501):
  if i % 2 != 0 and i % 3 == 0:
    soma += i
print(f"A soma dos números ímpares múltiplos de três entre 1 e 500 é: {soma}")

"""**2**) Desenvolver um algoritmo que leia a altura de 15 pessoas. Este programa deverá calcular e
mostrar :
a. A menor altura do grupo;
b. A maior altura do grupo;
"""

menor_altura = float('inf')
maior_altura = float('-inf')

for i in range(15):
    altura = float(input(f"Digite a altura da pessoa {i + 1} em metros: "))

    if altura < menor_altura:
        menor_altura = altura
    if altura > maior_altura:
        maior_altura = altura

print(f"A menor altura do grupo é: {menor_altura:.2f} metros")
print(f"A maior altura do grupo é: {maior_altura:.2f} metros")

"""*3*) Desenvolver um algoritmo que leia um número não determinado de valores e calcule e escreva a
média aritmética dos valores lidos, a quantidade de valores positivos, a quantidade de valores
negativos e o percentual de valores negativos e positivos.

"""

valores = []
quantidade_positivos = 0
quantidade_negativos = 0

while True:
    valor = float(input("Digite um valor (ou digite 0 para terminar): "))

    if valor == 0:
        break

    valores.append(valor)

    if valor > 0:
        quantidade_positivos += 1
    elif valor < 0:
        quantidade_negativos += 1

if valores:
    media = sum(valores) / len(valores)
    percentual_positivos = (quantidade_positivos / len(valores)) * 100
    percentual_negativos = (quantidade_negativos / len(valores)) * 100

    print(f"Média aritmética dos valores lidos: {media:.2f}")
    print(f"Quantidade de valores positivos: {quantidade_positivos}")
    print(f"Quantidade de valores negativos: {quantidade_negativos}")
    print(f"Percentual de valores positivos: {percentual_positivos:.2f}%")
    print(f"Percentual de valores negativos: {percentual_negativos:.2f}%")
else:
    print("Nenhum valor foi lido.")

#misericódia

"""4) Escrever um algoritmo que leia uma quantidade desconhecida de números e conte quantos deles
estão nos seguintes intervalos: [0-25], [26-50], [51-75] e [76-100]. A entrada de dados deve
terminar quando for lido um número negativo.
"""

contagem_0_25 = 0
contagem_26_50 = 0
contagem_51_75 = 0
contagem_76_100 = 0

while True:
    numero = float(input("Digite um número (ou um número negativo para terminar): "))

    if numero < 0:
        break

    if 0 <= numero <= 25:
        contagem_0_25 += 1
    elif 26 <= numero <= 50:
        contagem_26_50 += 1
    elif 51 <= numero <= 75:
        contagem_51_75 += 1
    elif 76 <= numero <= 100:
        contagem_76_100 += 1

print(f"Números no intervalo [0-25]: {contagem_0_25}")
print(f"Números no intervalo [26-50]: {contagem_26_50}")
print(f"Números no intervalo [51-75]: {contagem_51_75}")
print(f"Números no intervalo [76-100]: {contagem_76_100}")

#vixi

"""5) Faça um algoritmo estruturado que leia uma quantidade não determinada de números positivos.
Calcule a quantidade de números pares e ímpares, a média de valores pares e a média geral dos
números lidos. O número que encerrará a leitura será zero.
6
"""

quantidade_pares = 0
quantidade_impares = 0
soma_pares = 0
soma_total = 0
contagem_total = 0

while True:
    numero = float(input("Digite um número positivo (ou 0 para encerrar): "))

    if numero == 0:
        break

    if numero > 0:
        contagem_total += 1
        soma_total += numero

        if numero % 2 == 0:
            quantidade_pares += 1
            soma_pares += numero
        else:
            quantidade_impares += 1

if quantidade_pares > 0:
    media_pares = soma_pares / quantidade_pares
else:
    media_pares = 0

if contagem_total > 0:
    media_geral = soma_total / contagem_total
else:
    media_geral = 0

print(f"Quantidade de números pares: {quantidade_pares}")
print(f"Quantidade de números ímpares: {quantidade_impares}")
print(f"Média dos valores pares: {media_pares:.2f}")
print(f"Média geral dos números lidos: {media_geral:.2f}")

"""*6*) Escrever um algoritmo que gera e escreve os números ímpares entre 100 e 200"""

for numero in range(101, 200, 2):
    print(numero)

"""7) Escrever um algoritmo que leia um valor para uma variável N de 1 a 10 e calcule a tabuada de
N. Mostre a tabuada na forma: 0 x N = 0, 1 x N = 1N, 2 x N = 2N, ..., 10 x N = 10N.
"""

N = int(input("Digite um valor para N (de 1 a 10): "))

if 1 <= N <= 10:
    for i in range(11):
        print(f"{i} x {N} = {i * N}")
else:
    print("O valor de N deve estar entre 1 e 10.")

"""8) Escreva um algoritmo que leia um valor inicial A e uma razão R e imprima uma

*   Item da lista
*   Item da lista

seqüência em
P.A. contendo 10 valores.
"""

A = float(input("Digite o valor inicial A: "))
R = float(input("Digite a razão R: "))

for i in range(10):
    termo = A + i * R
    print(f"Item {i + 1}: {termo}")

"""9) Escreva um algoritmo que leia um valor inicial A e uma razão R e imprima uma seqüência em
P.G. contendo 10 valores.
"""

A = float(input("Digite o valor inicial A: "))
R = float(input("Digite a razão R: "))

for i in range(10):
    termo = A * (R ** i)
    print(f"Item {i + 1}: {termo}")

"""10) Escreva um algoritmo que leia um valor inicial A e imprima a seqüência de valores do cálculo de
A! e o seu resultado. Ex: 5! = 5 X 4 X 3 X 2 X 1 = 120
"""

import math

A = int(input("Digite um valor inicial A: "))

if A < 0:
    print("O valor deve ser um número inteiro não negativo.")
else:
    resultado = math.factorial(A)
    fatores = " x ".join(str(i) for i in range(A, 0, -1))
    print(f"{A}! = {fatores} = {resultado}")